language: android
jdk: oraclejdk8
sudo: false

branches:
  only:
    - gradle_openSSL_master

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - wget -O libjlibtorrent.so https://s3-ap-southeast-1.amazonaws.com/apkpure-travis-ci/so/libjlibtorrent.so
  - mkdir -p swig/bin/release/android/armeabi-v7a/
  - mv -f libjlibtorrent.so swig/bin/release/android/armeabi-v7a/

script: gradle build

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: build/libs
  acl: public_read
  upload-dir: so
  on:
    all_branches: true

notifications:
  email:
    - 964761087@qq.com
  template:
    - '构建成功jar包，快去下载吧！ (<a href="https://s3-ap-southeast-1.amazonaws.com/apkpure-travis-ci/jar/jlibtorrent-1.2.0.4.jar">jlibtorrent-1.2.0.4.jar</a>/<a href="https://s3-ap-southeast-1.amazonaws.com/apkpure-travis-ci/jar/jlibtorrent-android-arm-1.2.0.4.jar">jlibtorrent-android-arm-1.2.0.4.jar</a>)'
    format: html
#notifications:
#  email: false