language: android
jdk: oraclejdk8
sudo: required

branches:
  only:
    - gradle_openSSL_master

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

before_install:
  - wget -O libjlibtorrent.so https://s3-ap-southeast-1.amazonaws.com/apkpure-travis-ci/release/android/armeabi-v7a/libjlibtorrent.so
  - mkdir -p frostwire-jlibtorrent/swig/bin/release/android/armeabi-v7a/
  # - sudo chmod 777 swig/bin/release/android/armeabi-v7a/
  # - sudo chgrp -r swig/bin/release/android/armeabi-v7a/
  # - sudo chmod g+rwx swig/bin/release/android/armeabi-v7a/
  #xiongke15117937934/frostwire-jlibtorrent
  - mv -f libjlibtorrent.so frostwire-jlibtorrent/swig/bin/release/android/armeabi-v7a/

  - cd ..


script: gradle build

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: build/libs
  on:
    all_branches: true